version: '3.9'
services:
    core-api:
        build:
            context: .
            dockerfile: ./apps/core-api/Dockerfile
        env_file:
            - ./.env
        ports:
            - '8000:8000'
        restart: always
    panel-api:
        build:
            context: .
            dockerfile: ./apps/panel-api/Dockerfile
        env_file:
            - ./.env
        ports:
            - '8001:8001'
        restart: always
